version: '2'

services:
  chubbybunnies:
    environment:
      - PORT=5000
      - LOCAL_MONGODB_URL=mongodb://localhost/CRS-Capstone-Project-LocalDB
      - PROD_PYTHON_URL=https://ai.buksu-crs.systems
      - PROD_URL=https://buksu-crs.systems
      - MONGODB_URL=mongodb+srv://Admin:pYg96SY5pQrNUpIo@cluster0.urjcmww.mongodb.net/?retryWrites=true&w=majority
      - JWT_SECRET=Yum_<e7-S?SH9EMB}z56_L)U[$#,/P_)!ujGJYU4EN*"j+yDTH
      - CLIENT_ID=270040489280-ljn99nm3ve4m8su2t77dras268tp2fiu.apps.googleusercontent.com
      - AUTH_EMAIL=buksu.crs@gmail.com
      - AUTH_PASS=fewoqaxknakacupm
    container_name: buksu-crs.node
    labels:
    - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    image: chuyx/buksu-crs.node:latest
    ports:
      - "7400:5000"

  pythonbunnies:
    container_name: buksu-crs.python
    labels:
    - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    image: chuyx/buksu-crs.python:latest
    ports:
      - "7401:3000"