name: CI
on:
  push: 
    branches:
      - main
jobs: 
  main: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [main]
        uses: actions/checkout@v2
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      
      - name: Build and push node
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: chuyx/buksu-crs.node:latest

      
      - name: Build and push python
        uses: docker/build-push-action@v4
        with:
          file: ./DockerfilePython
          push: true
          tags: chuyx/buksu-crs.python:latest

          
        
      
